/// Generated by AssetsRefGenerator on 2020/10/20
class Res {
  static const String back = "assets/icons/back.svg";
  static const String cart_with_item = "assets/icons/cart_with_item.svg";
  static const String chat = "assets/icons/chat.svg";
  static const String notification = "assets/icons/notification.svg";
  static const String search = "assets/icons/search.svg";
  static const String attachment = "assets/images/attachment.gif";
  static const String loading = "assets/images/loading.gif";
  static const String logo = "assets/images/logo.png";
}
